# Generated by Django 3.0.7 on 2020-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories_exceeded',
            field=models.BooleanField(default=False),
        ),
    ]
