# Generated by Django 3.0.7 on 2020-06-21 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0003_auto_20200619_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='num_of_calories',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Minimum calories for a day should be 1.')]),
        ),
    ]
