# Generated by Django 3.0.7 on 2020-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0004_auto_20200621_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='num_of_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
