# Generated by Django 3.0 on 2020-07-10 08:06

from django.contrib.auth import models
from django.contrib.auth.models import Group, User
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models

from calorie_app.models import FoodItem, UserProfile


def create_groups(*args, **kwargs):
    groups = ['Administrator', 'User_Manager', 'Normal_User']
    options = ['add', 'change', 'view', 'delete']
    model_names = ['user', 'userprofile', 'fooditem']
    for group in groups:
        new_group = Group.objects.create(name=group)
        if group == 'Administrator':
            model_names = model_names[:]
        elif group == 'User_Manager':
            model_names = ['user', 'userprofile']
        elif group == 'Normal_User':
            model_names = ['user', 'userprofile', 'fooditem']
            print(model_names)
        for model in model_names:
            if model == "user":
                model_name = User
            elif model == "userprofile":
                model_name = UserProfile
            elif model == 'fooditem':
                model_name = FoodItem
            content_type = ContentType.objects.get_for_model(model_name)
            for option in options:
                new_permission, _ = models.Permission.objects.get_or_create(
                    codename=f'can_{option}_{model}',
                    name=f'can {option} {model}',
                    content_type=content_type
                )
                new_group.permissions.add(new_permission)

class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0005_auto_20200621_1342'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
